### ISSUE TITLE
mzR compilation failure on RHEL6 - missing boost/detail/fenv.hpp

### ISSUE THREAD

**Issue by hillan141** [sneumann/mzR#154] opened 2018-04-11 19:43 UTC
Hi maintainer(s),

Thanks for providing this mzR package.  On Red Hat Enterprise Linux 6, R 3.4.4, I find compilation fails with error message suggesting missing boost header.  Transcript of failed install below.  Can you assist?

Best,
Andrew.

```
> source("https://bioconductor.org/biocLite.R")
Bioconductor version 3.6 (BiocInstaller 1.28.0), ?biocLite for help
> biocLite("mzR", suppressUpdates=TRUE)
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.4 (2018-03-15).
Installing package(s) ‘mzR’
trying URL 'https://bioconductor.org/packages/3.6/bioc/src/contrib/mzR_2.12.0.tar.gz'
Content type 'application/x-gzip' length 5420945 bytes (5.2 MB)
==================================================
downloaded 5.2 MB

* installing *source* package ‘mzR’ ...
** libs
rm -f cramp.o ramp_base64.o ramp.o RcppRamp.o RcppRampModule.o rnetCDF.o RcppPwiz.o RcppPwizModule.o RcppIdent.o RcppIdentModule.o ./boost/libs/system/src/error_code.o ./boost/libs/regex/src/posix_api.o ./boost/libs/regex/src/fileiter.o ./boost/libs/regex/src/regex_raw_buffer.o ./boost/libs/regex/src/cregex.o ./boost/libs/regex/src/regex_debug.o ./boost/libs/regex/src/instances.o ./boost/libs/regex/src/icu.o ./boost/libs/regex/src/usinstances.o ./boost/libs/regex/src/regex.o ./boost/libs/regex/src/wide_posix_api.o ./boost/libs/regex/src/regex_traits_defaults.o ./boost/libs/regex/src/winstances.o ./boost/libs/regex/src/wc_regex_traits.o ./boost/libs/regex/src/c_regex_traits.o ./boost/libs/regex/src/cpp_regex_traits.o ./boost/libs/regex/src/static_mutex.o ./boost/libs/regex/src/w32_regex_traits.o ./boost/libs/iostreams/src/zlib.o ./boost/libs/iostreams/src/file_descriptor.o ./boost/libs/filesystem/src/operations.o ./boost/libs/filesystem/src/path.o ./boost/libs/filesystem/src/utf8_codecvt_facet.o ./boost/libs/chrono/src/chrono.o ./boost/libs/chrono/src/process_cpu_clocks.o ./boost/libs/chrono/src/thread_clock.o ./pwiz/data/msdata/Version.o ./pwiz/data/identdata/Version.o ./pwiz/data/common/MemoryIndex.o ./pwiz/data/common/CVTranslator.o ./pwiz/data/common/cv.o ./pwiz/data/common/ParamTypes.o ./pwiz/data/common/BinaryIndexStream.o ./pwiz/data/common/diff_std.o ./pwiz/data/common/Unimod.o ./pwiz/data/msdata/SpectrumList_MGF.o ./pwiz/data/msdata/DefaultReaderList.o ./pwiz/data/msdata/ChromatogramList_mzML.o ./pwiz/data/msdata/examples.o ./pwiz/data/msdata/Serializer_mzML.o ./pwiz/data/msdata/Serializer_MSn.o ./pwiz/data/msdata/Reader.o ./pwiz/data/msdata/Serializer_MGF.o ./pwiz/data/msdata/Serializer_mzXML.o ./pwiz/data/msdata/SpectrumList_mzML.o ./pwiz/data/msdata/SpectrumList_MSn.o ./pwiz/data/msdata/BinaryDataEncoder.o ./pwiz/data/msdata/Diff.o ./pwiz/data/msdata/MSData.o ./pwiz/data/msdata/References.o ./pwiz/data/msdata/SpectrumList_mzXML.o ./pwiz/data/msdata/IO.o ./pwiz/data/msdata/SpectrumList_BTDX.o ./pwiz/data/msdata/SpectrumInfo.o ./pwiz/data/msdata/RAMPAdapter.o ./pwiz/data/msdata/LegacyAdapter.o ./pwiz/data/msdata/SpectrumIterator.o ./pwiz/data/msdata/MSDataFile.o ./pwiz/data/msdata/MSNumpress.o ./pwiz/data/msdata/SpectrumListCache.o ./pwiz/data/msdata/Index_mzML.o ./pwiz/data/msdata/SpectrumWorkerThreads.o ./pwiz/data/identdata/IdentDataFile.o ./pwiz/data/identdata/IdentData.o ./pwiz/data/identdata/DefaultReaderList.o ./pwiz/data/identdata/Reader.o ./pwiz/data/identdata/Serializer_protXML.o ./pwiz/data/identdata/Serializer_pepXML.o ./pwiz/data/identdata/Serializer_mzid.o ./pwiz/data/identdata/IO.o ./pwiz/data/identdata/References.o ./pwiz/data/identdata/MascotReader.o ./pwiz/data/proteome/Modification.o ./pwiz/data/proteome/Digestion.o ./pwiz/data/proteome/Peptide.o ./pwiz/data/proteome/AminoAcid.o ./pwiz/utility/minimxml/XMLWriter.o ./pwiz/utility/minimxml/SAXParser.o ./pwiz/utility/chemistry/Chemistry.o ./pwiz/utility/chemistry/ChemistryData.o ./pwiz/utility/chemistry/MZTolerance.o ./pwiz/utility/misc/IntegerSet.o ./pwiz/utility/misc/Base64.o ./pwiz/utility/misc/IterationListener.o ./pwiz/utility/misc/MSIHandler.o ./pwiz/utility/misc/Filesystem.o ./pwiz/utility/misc/TabReader.o ./pwiz/utility/misc/random_access_compressed_ifstream.o ./pwiz/utility/misc/SHA1.o ./pwiz/utility/misc/SHA1Calculator.o ./pwiz/utility/misc/sha1calc.o ./random_access_gzFile.o ./RcppExports.o ./boost/libs/thread/src/pthread/once.o ./boost/libs/thread/src/pthread/thread.o rampR.o R_init_mzR.o
find . -name \*~ -exec rm {} \;   ## from cleanup
find . -name \*.o -exec rm {} \;  ## from cleanup
find . -name "#*#" -exec rm {} \; ## from cleanup
g++ -std=gnu++0x -I/app/R-3.4.4/lib64/R/include -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5   `nc-config --cflags || /bin/true`   -I"/app/R-3.4.4/lib64/R/library/Rcpp/include" -I"/app/R-3.4.4/lib64/R/library/zlibbioc/include" -I/usr/local/include   -fpic  -g -O2 -c cramp.cpp -o cramp.o
g++ -std=gnu++0x -I/app/R-3.4.4/lib64/R/include -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5   `nc-config --cflags || /bin/true`   -I"/app/R-3.4.4/lib64/R/library/Rcpp/include" -I"/app/R-3.4.4/lib64/R/library/zlibbioc/include" -I/usr/local/include   -fpic  -g -O2 -c ramp_base64.cpp -o ramp_base64.o
g++ -std=gnu++0x -I/app/R-3.4.4/lib64/R/include -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5   `nc-config --cflags || /bin/true`   -I"/app/R-3.4.4/lib64/R/library/Rcpp/include" -I"/app/R-3.4.4/lib64/R/library/zlibbioc/include" -I/usr/local/include   -fpic  -g -O2 -c ramp.cpp -o ramp.o
g++ -std=gnu++0x -I/app/R-3.4.4/lib64/R/include -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5   `nc-config --cflags || /bin/true`   -I"/app/R-3.4.4/lib64/R/library/Rcpp/include" -I"/app/R-3.4.4/lib64/R/library/zlibbioc/include" -I/usr/local/include   -fpic  -g -O2 -c RcppRamp.cpp -o RcppRamp.o
g++ -std=gnu++0x -I/app/R-3.4.4/lib64/R/include -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5   `nc-config --cflags || /bin/true`   -I"/app/R-3.4.4/lib64/R/library/Rcpp/include" -I"/app/R-3.4.4/lib64/R/library/zlibbioc/include" -I/usr/local/include   -fpic  -g -O2 -c RcppRampModule.cpp -o RcppRampModule.o
gcc -std=gnu99 -I/app/R-3.4.4/lib64/R/include -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5   `nc-config --cflags || /bin/true`   -I"/app/R-3.4.4/lib64/R/library/Rcpp/include" -I"/app/R-3.4.4/lib64/R/library/zlibbioc/include" -I/usr/local/include   -fPIC  -fPIC  -c rnetCDF.c -o rnetCDF.o
g++ -std=gnu++0x -I/app/R-3.4.4/lib64/R/include -DNDEBUG -I./boost_aux/ -I./boost/ -I. -D_LARGEFILE_SOURCE -DHAVE_PWIZ_MZML_LIB -D_NODEBUG -DWITHOUT_MZ5   `nc-config --cflags || /bin/true`   -I"/app/R-3.4.4/lib64/R/library/Rcpp/include" -I"/app/R-3.4.4/lib64/R/library/zlibbioc/include" -I/usr/local/include   -fpic  -g -O2 -c RcppPwiz.cpp -o RcppPwiz.o
In file included from ./boost/boost/math/special_functions/sign.hpp:16,
                 from ./boost/boost/lexical_cast/detail/inf_nan.hpp:34,
                 from ./boost/boost/lexical_cast/detail/converter_lexical_streams.hpp:64,
                 from ./boost/boost/lexical_cast/detail/converter_lexical.hpp:53,
                 from ./boost/boost/lexical_cast/try_lexical_convert.hpp:34,
                 from ./boost/boost/lexical_cast.hpp:32,
                 from ./pwiz/utility/misc/optimized_lexical_cast.hpp:29,
                 from ./pwiz/data/common/ParamTypes.hpp:29,
                 from pwiz/data/msdata/MSData.hpp:29,
                 from pwiz/data/msdata/MSDataFile.hpp:29,
                 from RcppPwiz.h:12,
                 from RcppPwiz.cpp:1:
./boost/boost/math/tools/config.hpp:339:36: error: boost/detail/fenv.hpp: No such file or directory
make: *** [RcppPwiz.o] Error 1
ERROR: compilation failed for package ‘mzR’
* removing ‘/app/R-3.4.4/lib64/R/library/mzR’

The downloaded source packages are in
        ‘/tmp/RtmpezGWCa/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘mzR’ had non-zero exit status
```

**Comment by sneumann** [comment] 2018-04-12 05:46
Hi, this looks like a duplicate of #100, which is fixed in the github version. 
You can get the package from here, or the fix will be in the next version we push to bioconductor.
Yours, Steffen

**Closed by sneumann** 2018-04-12 05:46 UTC
